name: instasave
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  awesome_notifications: ^0.10.0
  device_info_plus: ^11.1.1
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.5.0
  dio: ^5.0.2
  firebase_core: ^3.8.0
  file_picker: ^5.2.7
  firebase_messaging: ^15.1.5
  flutter_launcher_icons: ^0.13.0
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.2
  fluttertoast: ^8.2.1
#  gallery_saver: ^2.3.2
  image_gallery_saver: ^2.0.3
  get: ^4.6.6
  google_mobile_ads: ^5.2.0
  http: ^1.2.2
  in_app_review: ^2.0.6
#  internet_popup: ^1.0.8+5
  path_provider: ^2.0.13
  permission_handler: ^10.2.0
  provider: ^6.0.5
  shared_preferences: ^2.0.20
  sqflite: ^2.2.6
  share_plus: ^10.1.2
  receive_sharing_intent: ^1.4.5
  url_launcher: ^6.1.10
  video_player: ^2.6.0
  video_watermark:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/poppins_bold.ttf
    - family: PoppinsExtraBold
      fonts:
        - asset: assets/fonts/poppins_extra_bold.ttf
    - family: PoppinsLight
      fonts:
        - asset: assets/fonts/poppins_light.ttf
    - family: PoppinsMedium
      fonts:
        - asset: assets/fonts/poppins_medium.ttf
    - family: PoppinsRegular
      fonts:
        - asset: assets/fonts/poppins_regular.ttf
    - family: PoppinsSemiBold
      fonts:
        - asset: assets/fonts/poppins_semi_bold.ttf
